### ISSUE TITLE
Commands don't seem to work for context path which is deployed with a version

### ISSUE THREAD

**Issue by iamkevinv** [tomcatmanager/tomcatmanager#4]
I've wanted to get a time boxed session count from a particular running context but it doesn't seem to like it. I'm currently running the Python 2 branch.

```
$ tomcat-manager --user=myusername --password=mypassword http://myhost:8080/manager/text list

Path                           Status  Sessions
------------------------------ ------- --------
/                              running 0
/app                           running 8
/services-decom                running 0
/quote                         running 0
/monitor                       running 0
/manager                       running 44
```

Shows 8 running on app. The app context inside the Manager GUI is actually version described with PRO-20150520.1145 (tomcat parallel deployment war naming scheme).

```
$ tomcat-manager --user=myusername --password=mypassword http://myhost:8080/manager/text sessions /app

TomcatException: FAIL - No context exists for path /app
Traceback (most recent call last):
  File "/home/antdeploy/bin/tomcat-manager", line 626, in <module>
    sys.exit(main())
  File "/home/antdeploy/bin/tomcat-manager", line 615, in main
    itm.onecmd(command)
  File "/usr/lib64/python2.6/cmd.py", line 219, in onecmd
    return func(arg)
  File "/home/antdeploy/bin/tomcat-manager", line 429, in do_sessions
    for line in sesslist:
TypeError: 'NoneType' object is not iterable
```

But! Using a non versioned war, like the manager itself:

```
$ tomcat-manager --user=myusername --password=mypassword http://myhost:8080/manager/text sessions /manager

Default maximum session inactive interval 30 minutes
<1 minutes: 2 sessions
1 - <2 minutes: 2 sessions
5 - <6 minutes: 2 sessions
8 - <9 minutes: 8 sessions
9 - <10 minutes: 14 sessions
11 - <12 minutes: 9 sessions
14 - <15 minutes: 8 sessions
15 - <16 minutes: 3 sessions
```

Everything's working.

So I'm assuming it's not sure which docbase/versioned war it's looking for? Guessing really.
Might require the ability to specify app##PRO-20150520.1145.war or such? (also it would be great to get that war naming, or just the versions, listed in the 'list' option too.

Similar messages for other commands that require the 'path' like reload.

**Comment by kevdesign** [comment]
I was using another tool and just thought, perhaps this isn't entirely a bug - if i was to specify
    /app##PRO-20150520.1145
Would it pick that up? Is that really all which might be needed? In this case if the path column in the 'list' option would display it... it might be more self explanatory.

**Comment by kotfu** [comment]
I am not super familiar with the versioned wars, I understand the idea in principle, but I've never built or deployed one. The tomcat-manager python script talks to the manager app running inside tomcat via http. So for us to get any more information, the manager app that comes with tomcat will have to expose the data. I dug around a bit, and I think you were right in your guess about using the two hashmarks between the app and the version. This [stack overflow](http://stackoverflow.com/questions/6347326/web-app-version-in-tomcat-manager) question seems to indicate that your assumption is correct. This [section of the tomcat documentation](http://tomcat.apache.org/tomcat-7.0-doc/config/context.html#naming) also seems to indicate you have this correct.

So, here's a test you can do, since I don't have any versioned tomcat apps. Run the following command against your tomcat, and post the results:

```
curl --user=tm:thepass http://localhost:8080/manager/text/list
```
You should get something back like this:
```
OK - Listed applications for virtual host localhost
/:running:0:ROOT
/manager:running:16:/usr/share/tomcat7-admin/manager
/host-manager:running:0:/usr/share/tomcat7-admin/host-manager
```

The "list" command in the tomcat-manager python script hits that same URL, and then parses up the output.

I have noticed that on my tomcat7 test instance, there is now a file system path after the number of sessions. I'm hoping that your instance with the versioned war gives some more info there.

**Comment by kevdesign** [comment]
Using /app##PRO-20150520.1145 works to get details for it in the path :) I'll see if i can get a list at some point...

**Comment by johanhaleby** [comment]
Did anyone manage to solve this? Running into the same issue.

**Comment by kotfu** [comment]
At this point I am unaware of a solution, but I haven't been able to find anyone with versioned wars who can do some testing and exploration to see if we can get the data. Do you have a tomcat instance you would be willing to do some tests on?

**Comment by johanhaleby** [comment]
@kotfu Sure I think I will be able to help out

**Comment by kotfu** [comment]
@johanhaleby OK, try this test on your tomcat instance. Run the following command against your tomcat, and post the results:

```
curl --user=tm:thepass http://localhost:8080/manager/text/list
```
You should get something back like this:
```
OK - Listed applications for virtual host localhost
/:running:0:ROOT
/manager:running:16:/usr/share/tomcat7-admin/manager
/host-manager:running:0:/usr/share/tomcat7-admin/host-manager
```

**Comment by johanhaleby** [comment]
@kotfu I'll try to look into it tomorrow

**Comment by johanhaleby** [comment]
@kotfu This is what I get:

```bash
OK - Listed applications for virtual host localhost
/host-manager:running:0:/usr/share/tomcat7-admin/host-manager
/manager:running:0:/usr/share/tomcat7-admin/manager
/:running:1:ROOT##365
```
